plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
remote_theme: pages-themes/merlot@v0.2.0
show_downloads: true
title: Json-Database
description: Json-Database is an npm package for creating NoSQL JSON databases offline, allowing developers to store and retrieve data locally with ease.